// <auto-generated />
using System;
using Kalayci.Data.Concrete.EntityFrameWork.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kalayci.Data.Migrations
{
    [DbContext(typeof(KalayciContext))]
    [Migration("20250602204118_PersonelProjectNew")]
    partial class PersonelProjectNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kalayci.Entities.Concrete.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchDetay")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchDetay = "Bilgi işlem departmanı, şirketin bilgi teknolojileri altyapısını yönetir ve destekler.",
                            BranchName = "Bilgi işlem",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2025, 6, 2, 23, 41, 17, 376, DateTimeKind.Local).AddTicks(6969),
                            IsDeleted = false,
                            ModifiedByName = "System",
                            ModifiedDate = new DateTime(2025, 6, 2, 23, 41, 17, 376, DateTimeKind.Local).AddTicks(6968)
                        },
                        new
                        {
                            Id = 2,
                            BranchDetay = "Boru Donatım Mühendisi.",
                            BranchName = "Mühendis",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2025, 6, 2, 23, 41, 17, 376, DateTimeKind.Local).AddTicks(7014),
                            IsDeleted = false,
                            ModifiedByName = "System",
                            ModifiedDate = new DateTime(2025, 6, 2, 23, 41, 17, 376, DateTimeKind.Local).AddTicks(7013)
                        });
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.CircuitDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Dimensioning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Grinding")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PressureTest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("QualityControl")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WeldingTest")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("spoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("spoolId")
                        .IsUnique();

                    b.ToTable("CircuitDelivery");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.CircuitList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CircuitList");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.EmployeeExit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FinishWorkTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<byte>("PersonelNoteAverage")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("StartWorkTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("EmployeeExits");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.KalayciRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "e62c6ba9-80e7-4dca-a75e-ab1de77b649f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "8e407950-b816-44c7-99b3-998df1c1c260",
                            Name = "Yonetici",
                            NormalizedName = "YONETICI"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "a048cb1e-bc74-4dc6-8554-8ea6b8ce269e",
                            Name = "Muhendis",
                            NormalizedName = "MUHENDIS"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "7e116ea3-2538-44d4-aa58-a95477ed2f35",
                            Name = "Atolye",
                            NormalizedName = "ATOLYE"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "4ab48841-dfd9-4db7-a397-d1ee67d4f33e",
                            Name = "Müşteri",
                            NormalizedName = "MUSTERI"
                        });
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.KalayciUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Linkedin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordBackUp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("personelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("personelId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("OverallScore")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Picture")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("SgkRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("TcNumber")
                        .HasColumnType("longtext");

                    b.Property<byte>("TechnicalPoint")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("WorkFinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WorkStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("branchId");

                    b.ToTable("Personel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2025, 6, 2, 23, 41, 17, 380, DateTimeKind.Local).AddTicks(5351),
                            Gender = false,
                            IsDeleted = false,
                            LastName = "İşlem",
                            ModifiedByName = "System",
                            ModifiedDate = new DateTime(2025, 6, 2, 23, 41, 17, 380, DateTimeKind.Local).AddTicks(5354),
                            Name = "Bilgi",
                            OverallScore = (byte)0,
                            Phone = "555 004 63 33",
                            TechnicalPoint = (byte)0,
                            WorkFinishDate = new DateTime(2125, 6, 2, 23, 41, 17, 380, DateTimeKind.Local).AddTicks(5357),
                            WorkStartDate = new DateTime(2025, 6, 2, 23, 41, 17, 380, DateTimeKind.Local).AddTicks(5356),
                            branchId = 1
                        });
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.PersonelProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActiveWork")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PersonelProjects");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GiveDateFinish")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GiveDateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KalayciUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<byte>("SavePoint")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UserGivePoint")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KalayciUserId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ProjectFinishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ProjectStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("shipYardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("shipYardId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Sending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Place")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("spoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("spoolId")
                        .IsUnique();

                    b.ToTable("Sending");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.ShipYard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PersonelID")
                        .HasColumnType("int");

                    b.Property<string>("ShipYardManagementName")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipYardName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelID");

                    b.ToTable("ShipYard");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.ShipyardAssembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SpoolAssemblyByName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("SpoolAssemblyDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("spoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("spoolId")
                        .IsUnique();

                    b.ToTable("ShipyardAssembly");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Spool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CircuitListId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte>("Shipmentlocation")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("SpoolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("spoolStatus")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CircuitListId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Spool");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Welding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("SpoolWeldingType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("spoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("spoolId")
                        .IsUnique();

                    b.ToTable("Welding");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.WorkPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SpoolCreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("spoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("spoolId")
                        .IsUnique();

                    b.ToTable("WorkPlace");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.CircuitDelivery", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Spool", "spool")
                        .WithOne("CircuitDelivery")
                        .HasForeignKey("Kalayci.Entities.Concrete.CircuitDelivery", "spoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spool");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.EmployeeExit", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Personel", "Personel")
                        .WithMany("employeeExits")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.KalayciUser", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Branch", null)
                        .WithMany("KalayciUsers")
                        .HasForeignKey("BranchId");

                    b.HasOne("Kalayci.Entities.Concrete.Personel", "personel")
                        .WithOne("User")
                        .HasForeignKey("Kalayci.Entities.Concrete.KalayciUser", "personelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personel");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Personel", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", "ManagerUser")
                        .WithMany("ManagePersonel")
                        .HasForeignKey("ManagerUserId");

                    b.HasOne("Kalayci.Entities.Concrete.Branch", "branch")
                        .WithMany("Personels")
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerUser");

                    b.Navigation("branch");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.PersonelProject", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Branch", "Branch")
                        .WithMany("personelProjects")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kalayci.Entities.Concrete.Personel", "Personel")
                        .WithMany("PersonelProjects")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kalayci.Entities.Concrete.Project", "Project")
                        .WithMany("PersonelProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Personel");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Point", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", null)
                        .WithMany("Points")
                        .HasForeignKey("KalayciUserId");

                    b.HasOne("Kalayci.Entities.Concrete.Personel", "Personel")
                        .WithMany("points")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Project", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.HasOne("Kalayci.Entities.Concrete.ShipYard", "shipYard")
                        .WithMany("Projects")
                        .HasForeignKey("shipYardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("shipYard");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Sending", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Spool", "spool")
                        .WithOne("Sending")
                        .HasForeignKey("Kalayci.Entities.Concrete.Sending", "spoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spool");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.ShipYard", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.ShipyardAssembly", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Spool", "spool")
                        .WithOne("ShipyardAssembly")
                        .HasForeignKey("Kalayci.Entities.Concrete.ShipyardAssembly", "spoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spool");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Spool", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.CircuitList", "CircuitList")
                        .WithMany("spoolLists")
                        .HasForeignKey("CircuitListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kalayci.Entities.Concrete.Project", "Project")
                        .WithMany("spoolLists")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircuitList");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Welding", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Spool", "spool")
                        .WithOne("Welding")
                        .HasForeignKey("Kalayci.Entities.Concrete.Welding", "spoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spool");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.WorkPlace", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.Spool", "spool")
                        .WithOne("WorkPlace")
                        .HasForeignKey("Kalayci.Entities.Concrete.WorkPlace", "spoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spool");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Kalayci.Entities.Concrete.KalayciUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Branch", b =>
                {
                    b.Navigation("KalayciUsers");

                    b.Navigation("Personels");

                    b.Navigation("personelProjects");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.CircuitList", b =>
                {
                    b.Navigation("spoolLists");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.KalayciUser", b =>
                {
                    b.Navigation("ManagePersonel");

                    b.Navigation("Points");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Personel", b =>
                {
                    b.Navigation("PersonelProjects");

                    b.Navigation("User");

                    b.Navigation("employeeExits");

                    b.Navigation("points");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Project", b =>
                {
                    b.Navigation("PersonelProjects");

                    b.Navigation("spoolLists");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.ShipYard", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Kalayci.Entities.Concrete.Spool", b =>
                {
                    b.Navigation("CircuitDelivery");

                    b.Navigation("Sending");

                    b.Navigation("ShipyardAssembly");

                    b.Navigation("Welding");

                    b.Navigation("WorkPlace");
                });
#pragma warning restore 612, 618
        }
    }
}
